In [48]:
import pandas as pd
import numpy as np
import scipy


In [43]:
df = pd.read_csv('./data/blood_drive_data.csv')

In [81]:
from sklearn.preprocessing import Normalizer
columns = ['Months since Last Donation', 'Number of Donations', 'Total Volume Donated (c.c.)', 'Months since First Donation', 'Made Donation in March 2007']

array = df.values
X = array[:,0:4]
Y = array[:,4]

print(X)

scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

np.set_printoptions(precision=3)

[[  619     2    50 12500]
 [  664     0    13  3250]
 [  441     1    16  4000]
 ..., 
 [  360    21     2   500]
 [  541    39     1   250]
 [   74    72     1   250]]


//anaconda/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the normalize function.
  warnings.warn(msg, DataConversionWarning)


In [82]:
test = pd.read_csv('./data/test.csv')
from sklearn.neighbors import KNeighborsClassifier 
neigh = KNeighborsClassifier(n_neighbors = 3) 
neigh.fit(X, Y)

logistic_clf.predict_proba(test)[0:,1]

ValueError: X has 5 features per sample; expecting 4